"""create budgets, pots and recurring_bills tables

Revision ID: 96c7148d14af
Revises: 072b4bc4909d
Create Date: 2026-07-14 14:44:53.469656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c7148d14af'
down_revision = '072b4bc4909d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_amount', sa.Integer(), nullable=False),
    sa.Column('total_saved', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pots_user_id'), ['user_id'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('max_spend', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', name='uq_budgets_user_id_category_id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_user_id'), ['user_id'], unique=False)

    op.create_table('recurring_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_bills_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_bills_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_bills_user_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_bills_category_id'))

    op.drop_table('recurring_bills')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_user_id'))
        batch_op.drop_index(batch_op.f('ix_budgets_category_id'))

    op.drop_table('budgets')
    with op.batch_alter_table('pots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pots_user_id'))

    op.drop_table('pots')
    # ### end Alembic commands ###
